### ISSUE TITLE
Critical error on Balancehelper.py

### ISSUE THREAD

**Issue by Nevtep** [OmniLayer/omniwallet#1204]
When SX fails to return btc balances, the code has two references to an unbound variable

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 327, in run
    result = self._run(_self.args, *_self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/socketio/virtsocket.py", line 403, in _receiver_loop
    retval = pkt_ns.process_packet(pkt)
  File "/usr/local/lib/python2.7/dist-packages/socketio/namespace.py", line 155, in process_packet
    return self.process_event(packet)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 64, in process_event
    return self.socketio._dispatch_message(app, self, message, args)
  File "/usr/local/lib/python2.7/dist-packages/flask_socketio/__init__.py", line 137, in _dispatch_message
    ret = self.messages[namespace.ns_name][message](*args)
  File "websocket.py", line 106, in add_address
    balance_data=get_balancedata(address)
  File "/home/ubuntu/omniwallet/api/balancehelper.py", line 55, in get_balancedata
    btc_balance[ 'value' ] = int(-555)
UnboundLocalError: local variable 'btc_balance' referenced before assignment
<Greenlet at 0x7f93ee439730: <bound method Socket._receiver_loop of <socketio.virtsocket.Socket object at 0x7f93eec10550>>> failed with UnboundLocalError

This causes the websocket server to crash, renaming btc_balance to res should fix the problem.

**Comment by achamely** [comment]
sx no longer used for balance, issue resolved by migrating to new balance lookups
